# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SharifBible.com
email: info@sharifbible.com
description: >- # this means to ignore newlines until "baseurl:"
  The Sharif Bible is the complete Bible in modern Arabic. It is a dynamic translation, 
  and attempts to transfer the meaning of the original text into simple, modern, standard, 
  literary Arabic. This is meant to be understandable across the Arab world, so regional
  words and expressions are avoided. This translation holds dearly to being as accurate 
  and faithful to the original text as possible, natural (in language familiar to the reader), 
  clear, and easy to understand. It is an accurate translation of the original Hebrew and 
  Greek texts into the people's simple language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sharifbible
github_username:  sharifbibleadmin
defaults:
  - scope: 
      path: "images"
    values:
      image: true

# Build settings
markdown: kramdown
sass:
  sass_dir: css
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
